---

- name: Setup Development Machine
  hosts: localhost

  tasks:
    - name: Install common dependencies
      package:
        name:
          - rsync
        state: present
      become: true

    - name: Platform specific tasks
      include_tasks:
        file: "{{ ansible_facts['os_family'] | lower }}.yml"
        apply:
          become: true

    - name: Install neovim
      include_tasks: neovim.yml

    - name: Install fish
      include_tasks: fish.yml
