---

- name: Setup Development Machine
  hosts: localhost

  tasks:
    - name: Install common dependencies
      package:
        name:
          - rsync
          - tmux
        state: present
      become: true

    - name: Platform specific tasks
      include_tasks:
        file: "{{ ansible_facts['os_family'] | lower }}.yml"
        apply:
          become: true
      tags:
        - platform

    - name: Install neovim
      include_tasks:
        file: neovim.yml
        apply:
          tags:
            - neovim
      tags:
        - neovim

    - name: Install fish
      include_tasks:
        file: fish.yml
        apply:
          tags:
            - fish
      tags:
        - fish

    - name: Brew
      include_tasks: brew.yml
      tags:
        - brew

    - name: Flatpak
      include_tasks:
        file: flatpak.yml
        apply:
          tags: flatpak
      tags:
        - flatpak
