---

- name: Install fish
  become: true
  package:
    name: fish
    state: latest

- name: Download oh-my-fish
  get_url:
    url: https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install
    dest: /tmp/omf-install.sh
    mode: 0755
    force: true

- name: Download fundle
  get_url:
    url: https://git.io/fundle
    dest: "{{ lookup('env', 'HOME') }}/.config/fish/functions/fundle.fish"

- name: Install oh-my-fish
  shell:
    cmd: /tmp/omf-install.sh --yes --noninteractive
    executable: /bin/fish

- name: Set user shell
  become: true
  user:
    name: ghutton
    shell: /bin/fish
