- set_fact:
    download_location: /tmp/neovim.tar.gz

- name: Download neovim release
  get_url:
    url: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
    dest: "{{ download_location }}"

- name: Unarchive
  unarchive:
    src: "{{ download_location }}"
    dest: /tmp/

- name: Install
  synchronize:
    src: /tmp/neovim-linux64/{{ item }}/
    dest: /{{ item }}/
  loop:
    - bin
    - share
    - lib
    - man

- name: Install plugins
  shell:
    cmd: nvim --headless '+Lazy install' +q
