---

- name: Install tools
  dnf:
    name:
      - make
      - jq
      - wget
      - golang
      - kernel-devel
      - cmake
      - clang
      - flatpak
      - gcc
      # - https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: latest
