---

- name: Set up machine for development
  hosts: all

  tasks:
    - name: Install packages
      become: true
      package:
        name:
          - git
          - cmake
          - clang
          - golang
          - rust
        state: present

    - name: Download Neovim
      become: true
      shell: |
        if [[ ! -d /squashfs-root/ ]]; then
          curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
          chmod u+x nvim.appimage
          ./nvim.appimage --appimage-extract
          mv squashfs-root /
          ln -s /squashfs-root/AppRun /usr/bin/nvim
        fi

    - name: Clone Configs
      shell: |
        if [[ ! -d "$HOME/.cfg" ]]; then
          alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
          echo '.cfg' >> $HOME/.gitignore
          git clone --bare https://github.com/Stringy/configs $HOME/.cfg
          config checkout
          config config --local status.showUntrackedFiles no
        fi

    - name: Setup neovim
      shell: |
        git clone --depth 1 https://github.com/wbthomason/packer.nvim\
          ~/.local/share/nvim/site/pack/packer/start/packer.nvim

        nvim --headless +PackerInstall +q
