all:
  hosts:
    fedora:
      ansible_host: 192.168.56.2
      ansible_user: vagrant
      ansible_ssh_private_key_file: "{{ lookup('env', 'DEV_VM_DIR', default='/Users/ghutton/.var/qemu/fedora/id_rsa') }}"
